### PR TITLE
Remove failure:ignore tag for s390x pipeline

### PR DESCRIPTION
**Pull request by rohitsakala**
This is done since s390x support is being planned for GA

### CODE REVIEW

**Review by nikolaishields — APPROVED** [review]

**Review by matttrach — APPROVED** [review]

**Comment by briandowns** [comment]
Branch needs to have merge conflicts resolved before merging.

**Review by nikolaishields — CHANGES_REQUESTED** [review]
Looks like there's a merge conflict starting on line 75, other than that looks great!

**Comment by matttrach** [comment]
this appears to be a trivial conflict, @rohitsakala please review before merge

**Comment by matttrach** [comment]
Merged and rebased to get this change up to date and ready. @rohitsakala, would you mind taking a look to make sure this is still what you need?

**Comment by rohitsakala** [comment]
Approved

**Pull request merged**
